# Modified version of https://github.com/PX4/PX4-containers/blob/master/docker/Dockerfile_simulation-jammy with added Nvidia GPU support for higher frame rate simulations

FROM px4io/px4-dev-base-jammy:2024-05-18

WORKDIR /home/sim

ENV QT_X11_NO_MITSHM=1
ENV JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"

RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] https://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get -y --quiet --no-install-recommends install \
        ant \
        binutils \
        bc \
        dirmngr \
        gz-harmonic \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        libeigen3-dev \
        libgstreamer-plugins-base1.0-dev \
        libimage-exiftool-perl \
        libopencv-dev \
        libxml2-utils \
        mesa-utils \
        libgl1-mesa-glx \
        libgl1-mesa-dri \
        libglx-mesa0 \
        libglapi-mesa \
        protobuf-compiler \
        x-window-system \
    && apt-get -y autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN groupadd -g 1002 gazebosim && \
    useradd -u 1002 -g gazebosim -m -s /bin/bash sim && \
    chown sim /home/sim
USER sim

RUN git clone -q https://github.com/PX4/PX4-Autopilot.git PX4-Autopilot

RUN pip install kconfiglib jinja2 empy jsonschema pyros-genmsg packaging toml numpy future

WORKDIR /home/sim/PX4-Autopilot/
RUN git submodule update --init --recursive
RUN make px4_sitl_default

COPY ./worlds/* Tools/simulation/gz/worlds/

ENTRYPOINT ["make"]
CMD ["px4_sitl", "gz_x500_mono_cam"]